### ISSUE TITLE
Add game sounds

### ISSUE THREAD

**Issue by Ibrahim2750mi** [Sahaj001/Businesslike_Buffalo#30]
- [ ] Player move
- [ ] background music
- [ ] wind noises when player approaches a tree
- [ ] narrator's voice
- [ ] water noises when player approaches a lake

Any more sound suggestions are welcome.

**Comment by Ibrahim2750mi** [comment]
add the link of the sounds here, axthe you might want to work on the narrator voice part aka text to speech

**Comment by VeckoTheGecko** [comment]
Completed
