### ISSUE TITLE
Rendering issue in Windows cmd

### ISSUE THREAD

**Issue by VeckoTheGecko** [Sahaj001/Businesslike_Buffalo#35]
UTF8 characters used for collision detection not being rendered properly.

![Main screen](https://user-images.githubusercontent.com/36369090/125825469-925351d8-c2fc-4a2c-869c-fa19fb64590b.png)

A fix would be to change the way collision detection works, such that there is another file for each ascii art that specifies whether the object at that part is collidable.

Tree:
```
  888
 88&08
80&00&8
  )⠀(
```

Collision file for tree:
```
0011100
0111110
1111111
0011100
```

**Comment by Ibrahim2750mi** [comment]
fix applied
