### ISSUE TITLE
Inserting objects on edge of screen causes error

### ISSUE THREAD

**Issue by VeckoTheGecko** [Sahaj001/Businesslike_Buffalo#39]
An error in the rendering method and how the grids are indexed prevents objects from being inserted on the edges of the screen.

ie. A model being inserted into `(29,29)` of a `(30,30)` grid will cause an error as the method tries to place in indexes that don't exist.

It would be good to update the array such that it truncates the object so that it looks like it is going off the screen.

**Comment by VeckoTheGecko** [comment]
Let me know what you think @Ibrahim2750mi and whether this is worth fixing.

Might be better to just leave it and make sure things don't flow off the screen when making the map. Although this can make the forest not look as nice.

**Comment by Ibrahim2750mi** [comment]
can we just work now on neceesary things rather than re-editing the rendering stuff
