### ISSUE TITLE
Box around the game that the player can't escape

### ISSUE THREAD

**Issue by VeckoTheGecko** [Sahaj001/Businesslike_Buffalo#7]
The box defining the play area. This will be on screens 1-9 (excluding the main screen 5)
![Game Screens](https://user-images.githubusercontent.com/36369090/125169071-20d74b80-e1db-11eb-925e-98a8d886cee0.png)

Implementation is still a WIP, please add if you have ideas.

**Comment by JRavi2** [comment]
Closing as completed in #19
